const PDFDocument = require('pdfkit');
const fs = require('fs');

const generateInterviewReport = (interviewData, res) => {
    const doc = new PDFDocument();

    // Pipe directly to response
    doc.pipe(res);

    // Header
    doc.fontSize(25).text('InView AI - Assessment Report', { align: 'center' });
    doc.moveDown();

    // Candidate Info
    doc.fontSize(14).text(`Candidate: ${interviewData.candidateName}`);
    doc.text(`Job Role: ${interviewData.jobTitle}`);
    doc.text(`Date: ${new Date().toLocaleDateString()}`);
    doc.moveDown();

    // Scores
    doc.fontSize(18).text('Performance Summary');
    doc.fontSize(12);
    doc.text(`AI Behavioral Score: ${interviewData.aiScore}/100`);
    doc.text(`Technical Score: ${interviewData.codeScore || 'N/A'}/100`);
    doc.text(`Final Fit Score: ${interviewData.totalScore}/100`);
    doc.moveDown();

    // Section: Behavioral Analysis
    doc.fontSize(16).text('Behavioral Insights');
    doc.fontSize(10);
    doc.text(`Confidence: ${interviewData.insights?.confidence || 'High'}`);
    doc.text(`Nervousness: ${interviewData.insights?.nervousness || 'Low'}`);
    doc.text(`Eye Contact: ${interviewData.insights?.eyeContact || 'Steady'}`);
    doc.moveDown();

    // Section: Technical
    doc.fontSize(16).text('Technical Assessment');
    doc.fontSize(10);
    if (interviewData.codeSubmission) {
        doc.text('Code Submission:');
        doc.font('Courier').text(interviewData.codeSubmission);
    } else {
        doc.text('No code submission recorded.');
    }

    // Footer
    doc.font('Helvetica').fontSize(10).text('Generated by InView AI System', 50, 700, { align: 'center' });

    doc.end();
};

module.exports = {
    generateInterviewReport
};
